### ISSUE TITLE
Input-Remapper Nix OS Help

### ISSUE THREAD

**Issue by Myrkskog** [bphenriques/dotfiles#45]
I appreciate the help you provided earlier. Not sure why I haven't gotten it working. Your expanded explanation seemed clear enough.

Since I am working from someone's Nix OS dotfiles instead of starting from scratch. I may be misunderstanding their setup.

[](https://github.com/librephoenix/nixos-config)

I understand this is probably not the way to start using Nix OS.

I am going to commit my file changes in a fork of his repository soon.

As for the peripherals.nix I modified from your example.

{ home-manager, lib, userSettings, Config, ... }:
```

{
    xdg.configFile = {
      "input-remapper-2/config.json".source = config.lib.file.mkOutOfStoreSymlink "${hostDir}/input-remapper/config.json";
"input-remapper-2/presets/ROCCAT ROCCAT Kone XP Air Donhle/BLENDER copy.json".source = config.lib.file.mkOutOfStorSymlink "${hostDir}/input-remapper-2/BLENDER copy.json";
};

```
Defining hostDir = "/home/${userSettings.username}/.dotfiles/user/hardware";

It appears the symlinks were made. But I do not have new folders appearing in .../user/hardware alongside the peripherals.nix

I'm thinking these out of store files should be there so I can drop my finished input-remapper config files there.

Not sure I provided the correct information.

**Comment by bphenriques** [comment]
> Since I am working from someone's Nix OS dotfiles instead of starting from scratch. I may be misunderstanding their setup.
> I understand this is probably not the way to start using Nix OS.

Yeah, every setup is unique. Feel free to fork, however I suggest starting with a blank slate with three files: 
- `flake.nix`: defines the basic machine and import nixos/home-manager.
- `desktop.nix`: everything that relates to your host. It might contain a mixture of NixOS and Home-Manager
- (opt) `home.nix`: everything about your `$HOME`.  You can import using `imports = [./home.nix]`.

Sharing dotfiles is useful because you get some ideas and copy some snippets/patterns but not the whole thing usually.

> It appears the symlinks were made. But I do not have new folders appearing in .../user/hardware alongside the peripherals.nix
> I'm thinking these out of store files should be there so I can drop my finished input-remapper config files there.

Your files in store point should point to the absolute file `config.lib.file.mkOutOfStoreSymlink ...`. Input remapper will update the file for you, therefore I don't recommend changing by hand.

**Comment by bphenriques** [comment]
Plus, to be honest, if you are starting with Nix and programming in general you'll learn more by doing from scratch and copy (and adapt) patterns you (start to) understand. Nix has already a steep learning curve and you lack programming knowledge (according to you what I said), therefore I recommend doing in small steps 🙂

**Comment by Myrkskog** [comment]
Seeing how custom the flake.nix is, and the custom modules in their repository did scare me. 

I am slowly making sense of it. Unfortunately, I took the plunge and have to run with what I have currently, for better or worse. 

On my personal laptop I will start from scratch.

I didn't imagine input-remapper wouldn't just work. I saw the package being available and that convinced me of this.

I'll keep plugging away. Too bad I'm so reliant on these custom bindings to work! Otherwise I would leave it for another time.

Thanks again for the help and advice.

**Comment by bphenriques** [comment]
I don't have time this week but if you are still stuck I can look at creating a branch with the barebones structure.

**Comment by Myrkskog** [comment]
That would be fantastic! And if you cannot next week, or anytime for that matter, it is ok too 👍. I appreciate your willingness to help.

**Comment by Myrkskog** [comment]
Just when I think I have everything sorted. I get errors stating that options do not exist. I am absolutely missing something here. Feeling quite foolish.

**Comment by bphenriques** [comment]
> Just when I think I have everything sorted. I get errors stating that options do not exist. I am absolutely missing something here. Feeling quite foolish.

What does it say?

Suggestion:
1. Unmount the config files in your nix setup
2. Apply
3. Ensure no file is present in the input remapper config path (to avoid conflicts)
4. Run the input-remapper. It should work ok
5. Copy the file generated to your config
6. Mount the new new config files
7. Apply
8. It should fine as it was on step 4.

**Comment by Myrkskog** [comment]
This is what i am seeing when i attempt to run input-remapper.

` → input-remapper-gtk                                                                                                              ▂▄▆█▆▄▂
input-remapper-gtk 2.0.1 2.0.1 https://github.com/sezanzeb/input-remapper
python-evdev 1.7.0
==== AUTHENTICATING FOR org.freedesktop.policykit.exec ====
Authentication is needed to run `/nix/store/a4c4j8816hrmh1bmh2p8lrrh8jw ... ontrol --command start-reader-service' as the super user
Authenticating as: magoose
Password:
polkit-agent-helper-1: error response to PolicyKit daemon: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: No session for cookie
==== AUTHENTICATION FAILED ====
Error executing command as another user: Not authorized

This incident has been reported.
ERROR: Failed to pkexec the reader-service, code 32512`
